apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: testing1
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./testing1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system 
  validation: client
