apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sample
  namespace: default
spec:
  interval: 5m0s
  path: ./apps/sample
  prune: true
  sourceRef:
    kind: GitRepository
    name: sample
  validation: client
  patches:
    - patch: |-
        apiVersion: v1
        kind: Pod
        metadata:
          name: sample1
        spec:
          containers:
          - name: ubuntu
            image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu:latest
      target:
        name: sample
        kind: Pod
