apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client
  name: client
spec:
  containers:
  - image: busybox
    name: client
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
