apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: www-deploy
  name: www-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www-deploy
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
